import { ReactNode } from "react";
import HomeHeader from "@/components/homeheader";
import { Separator } from "@/components/ui/separator";
import { ModeToggle } from "@/components/theme-switch";
export const metadata = {
  title: "Dashboard | To Do App",
  description: "Generated by create next app",
};

type DashboardLayoutProps = {
  children: ReactNode;
  tabvalue: String;
};

export default function DashboardLayout({ children }: DashboardLayoutProps) {
  return (
    <>
      <HomeHeader />

      {children}
      <ModeToggle />
    </>
  );
}
