import { ReactNode } from "react";
import { Card } from "@/components/ui/card";
import { Tabs } from "@/components/ui/tabs";

import Dashboardheader from "./modules/dashboardheader";

export const metadata = {
  title: "Dashboard | To Do App",
  description: "Generated by create next app",
};

type DashboardLayoutProps = {
  children: ReactNode;
};

export default function DashboardLayout({ children }: DashboardLayoutProps) {
  return (
    <>
      <Tabs defaultValue="projects" className="grid grid-cols-7">
        <Dashboardheader />
        <section className=" col-span-6 m-10">
          <Card className="h-full p-10">{children}</Card>
        </section>
      </Tabs>
    </>
  );
}
