import { ReactNode } from "react";
import { Card } from "@/components/ui/card";
import { Tabs } from "@/components/ui/tabs";
import Dashboardheader from "../../dashboard/modules/dashboardheader";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";

export const metadata = {
  title: "Dashboard | To Do App",
  description: "Generated by create next app",
};

type DashboardLayoutProps = {
  children: ReactNode;
};

export default function DashboardLayout({ children }: DashboardLayoutProps) {
  return (
    <Tabs defaultValue="projects" className="grid grid-cols-7">
      <Dashboardheader />
      <section className="col-span-6 m-10">
        <Card className="w-full flex h-full p-10 overflow-auto">
          <ScrollArea className="w-[1850px] pb-10 ">
            {children}
            <ScrollBar orientation="horizontal" />
          </ScrollArea>
        </Card>
      </section>
    </Tabs>
  );
}
